### ISSUE TITLE
Timeline selection in the header

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#3]
Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

Add a "dropdown" to the header (top right) with a label "7 days", to indicate that all of the data is for the last week.

The dropdown will be disabled and it won't be possible to change it - initially only 7 days will be supported. There will be a new issue in the future to make this selector work.

To make things clear, also add a tooltip. After a user hovers on the selector, this text will pop up: "Currently only 7 day time frame is supported."

**Comment by fishonamos** [comment]
I will love to hop on this.

**Comment by jaipaljadeja** [comment]
I can take this.

**Comment by Mario-Araya** [comment]
@mazurroman Greetings! 🌟 I'm Mario Araya, and I'm eager to contribute to the development of Starkflare.

For this task, I intend to work on the header component of the Starkflare web application. Specifically, I'll be editing the relevant HTML, CSS, and possibly JavaScript files to implement the timeline selection feature in the header. This feature will allow users to select different timelines and view corresponding data.

I'll ensure that the implementation is user-friendly, responsive, and aligns with the overall design principles of Starkflare.

Excited to get started!

Warm regards,
Mario Araya

**Comment by danielcdz** [comment]
Hello! I would like to help with this one!
I think this issue can take me about 2 to 5 days to complete exactly the time limit of the OD Hack!
I have over 3 years of experience as a software engineer and I want to learn about web3 and blockchain, this is my 2nd OD Hack 🫡

**Comment by VictoriaAde** [comment]
Hi, I  have a good idea how this would work.
I would like to work on this.

**Comment by DanielEmmanuel1** [comment]
Hello @mazurroman My name is Daniel and I'm interested in taking up this tasks, after carefully reading the project requirements, I have come to the conclusion that since the dropdown will be disabled initially, this issue can easily be solved by using just plain html and CSS without any form of JavaScript at least until the new selector functionality issue is added and will need to start listening for various events.

If the issue of of functionality of the dropdown ever occurs I'll solve this by just creating a div in which I'll add all the menu items into the div in form of anchor tags and create an hover event that when a cursor hover over the menu it displays the div container containing the div anchor items.

I'll really love the opportunity to work on this project, considering this is my first time contributing to OD hack, i believe in my abilities to deliver this project with the utmost level of perfection.

**Comment by mazurroman** [comment]
Assigned to @Joy-Adah, thanks for the detailed comment and good luck! @jaipaljadeja was technically first but he already has two issues so I passed it on :)

Thanks to everyone else for your interest!

**Comment by Joy-Adah** [comment]
Thanks @mazurroman

**Comment by Benjtalkshow** [comment]
@mazurroman I will be available to work on the feature issues regarding making the selector to work.
