### ISSUE TITLE
Data tile BE: contracts burning most steps

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#5]
Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

### Update get_common_data function to include top contracts by steps

1. Modify the `get_common_data` function in the `starkflare-indexer` backend repository (https://github.com/walnuthq/starkflare-indexer) to include a new field called `top_contracts_by_steps` in the response.

2. The `top_contracts_by_steps` field should contain a list of the top 10 contracts that consumed the highest amount of steps over the last 7 days.

3. For each contract in the `top_contracts_by_steps` list, include the following data:
   - Contract hash
   - Number of steps consumed
   - Percentage of total steps consumed by the contract

4. Implement a new function to retrieve the top contracts by steps data and call it from within the `get_common_data` function.

5. Ensure that the `top_contracts_by_steps` field is added to the existing response format of `get_common_data` without modifying the other fields.

### Create Next.js server API endpoint for enhanced contracts data

1. Implement a new API endpoint in this Next.js repository that fetches data from the `starkflare-indexer` endpoint created in the previous step.

2. Enhance the data returned by the `starkflare-indexer` endpoint by adding contract names to the response. To obtain the contract names:
   - Use the Voyager API (https://docs.voyager.online) to fetch the contract names based on the contract hashes

3. The final response from this Next.js API endpoint should include:
   - Contract hash
   - Number of steps consumed
   - Percentage of total steps consumed by the contract
   - Contract name

4. Implement proper error handling and validation of the data received from the `starkflare-indexer` endpoint to ensure data integrity and reliability.

5. Follow Next.js best practices and coding conventions while implementing the API endpoint.

**Comment by addegbenga** [comment]
I will like to work on this

**Comment by jbmkahdeksan** [comment]
hi!
I am interested in contributing with this one. Could you please assign it to me when the moment  comes?

**Comment by mazurroman** [comment]
@jbmkahdeksan thanks for your comment! Since you are new to Walnut can you update it according to our [contributor guidelines](https://github.com/walnuthq/starkflare/issues/12).

**Comment by jbmkahdeksan** [comment]
Sure thing, @mazurroman!
Well, my name is Joaquin, web3 enthusiast from Costa Rica. In my way to transition full-time into web3. 
Part of my profile is to work in backend and "underground" things like infra. I have been contributing since the last two OD Hacks.

About the technical details on how to accomplish this issue, it seems to me that you are creating a way to query some top contracts. Instructions are well detailed in my opinion. Of course I will have to get familiar with the codebase. It doesn't seem like a heavy technical task, it is more like an extensive set of small sequential tasks. I have experience with TypeScript and JavaScript so language is not an issue.
Being honest there is a bit of learning curve for the second part of the task, but that's why I am here, to challenge myself while being useful to others. 
During the day I will be studying the codebase for this issue, I can come with a broader answer if necessary.

**Comment by princeibs** [comment]
c

**Comment by mazurroman** [comment]
@jbmkahdeksan thank you for the thorough comment, this issue is yours! Good luck with your first contribution, this task is not trivial :) Feel free to ask anything in our Telegram, we will be super happy to help
